name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: "T1WiLLi"
          outputs: "dist/github-snake.svg dist/github-snake-dark.svg dist/ocean.gif"


      - name: Upload Snake Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: snake-artifacts
          path: dist
